#!/usr/bin/env python3
"""Host replay of the actual MiniBalanLink class against deterministic Android fakes.

This is a state/queue contract test, not evidence of Android radio or UI acceptance.
Run with --java-home pointing to JDK 21 (no device, network or APK installation).
"""
import argparse
from pathlib import Path
import subprocess
import tempfile

STUBS = {
"android/os/Looper.java": '''package android.os; public class Looper { static final Looper MAIN=new Looper(); public static Looper getMainLooper(){return MAIN;} public static Looper myLooper(){return MAIN;} }''',
"android/os/Message.java": '''package android.os; public class Message { public int what,arg1,arg2; public Object obj; public void recycle(){} }''',
"android/os/Handler.java": '''package android.os;
import java.util.*;
public class Handler {
 public interface Callback { boolean handleMessage(Message m); }
 private Callback callback; public static long now; private static long seq;
 private static final List<Task> tasks=new ArrayList<>();
 static class Task { Handler h; Runnable r; long time,order; Task(Handler h,Runnable r,long t){this.h=h;this.r=r;time=t;order=seq++;} }
 public Handler(Looper l){} public Handler(Callback c){callback=c;}
 public boolean post(Runnable r){return postDelayed(r,0);}
 public boolean postDelayed(Runnable r,long d){tasks.add(new Task(this,r,now+d));return true;}
 public void removeCallbacks(Runnable r){tasks.removeIf(t->t.h==this&&t.r==r);}
 public Message obtainMessage(int what,Object obj){Message m=new Message();m.what=what;m.obj=obj;return m;}
 public void dispatchMessage(Message m){if(callback!=null)callback.handleMessage(m);}
 public static void advance(long ms){long end=now+ms;int guard=0;while(true){Task first=null;for(Task t:tasks)if(t.time<=end&&(first==null||t.time<first.time||(t.time==first.time&&t.order<first.order)))first=t;if(first==null)break;if(++guard>20000)throw new AssertionError("runaway tasks");tasks.remove(first);now=first.time;first.r.run();}now=end;}
}''',
"android/os/SystemClock.java": '''package android.os; public class SystemClock { public static long uptimeMillis(){return Handler.now;} }''',
"android/content/BroadcastReceiver.java": '''package android.content; public class BroadcastReceiver {}''',
"android/content/Context.java": '''package android.content; public class Context { public static final String BLUETOOTH_SERVICE="bluetooth";public int unregisters;public android.content.res.AssetManager assets=new android.content.res.AssetManager();public android.bluetooth.BluetoothManager manager=new android.bluetooth.BluetoothManager();public android.content.res.AssetManager getAssets(){return assets;}public Object getSystemService(String name){return manager;} public Context getApplicationContext(){return this;} public void unregisterReceiver(BroadcastReceiver r){if(++unregisters>1)throw new IllegalArgumentException();} }''',
"android/content/res/AssetManager.java": '''package android.content.res;import java.io.*;public class AssetManager {public String config;public InputStream open(String name)throws IOException{if(!name.equals("mvtbot-debug-autoconnect.properties"))throw new AssertionError("unexpected asset");if(config==null)throw new FileNotFoundException();return new ByteArrayInputStream(config.getBytes(java.nio.charset.StandardCharsets.US_ASCII));}}''',
"android/bluetooth/BluetoothManager.java": '''package android.bluetooth;public class BluetoothManager {public BluetoothAdapter adapter=new BluetoothAdapter();public BluetoothAdapter getAdapter(){return adapter;}}''',
"android/bluetooth/BluetoothAdapter.java": '''package android.bluetooth;public class BluetoothAdapter {public interface LeScanCallback{void onLeScan(BluetoothDevice d,int rssi,byte[] record);}public boolean enabled=true;public android.bluetooth.le.BluetoothLeScanner scanner=new android.bluetooth.le.BluetoothLeScanner();public boolean isEnabled(){return enabled;}public android.bluetooth.le.BluetoothLeScanner getBluetoothLeScanner(){return scanner;}public static boolean checkBluetoothAddress(String s){return s!=null&&s.matches("([0-9A-F]{2}:){5}[0-9A-F]{2}");}}''',
"android/bluetooth/le/ScanCallback.java": '''package android.bluetooth.le;import java.util.*;public class ScanCallback {public void onScanResult(int type,ScanResult result){}public void onBatchScanResults(List<ScanResult> results){}public void onScanFailed(int code){}}''',
"android/bluetooth/le/ScanResult.java": '''package android.bluetooth.le;import android.bluetooth.*;public class ScanResult {private BluetoothDevice device;public ScanResult(BluetoothDevice d){device=d;}public BluetoothDevice getDevice(){return device;}public int getRssi(){return -50;}public ScanRecord getScanRecord(){return new ScanRecord();}}''',
"android/bluetooth/le/ScanRecord.java": '''package android.bluetooth.le;public class ScanRecord{public byte[] getBytes(){return new byte[0];}}''',
"android/widget/PopupWindow.java": '''package android.widget;public class PopupWindow{public boolean showing=true;public boolean isShowing(){return showing;}}''',
"android/widget/Toast.java": '''package android.widget;import android.content.Context;import java.util.*;public class Toast{public static final int LENGTH_SHORT=0;public static final List<String> shown=new ArrayList<>();public static boolean denied;private String text;public static Toast makeText(Context c,CharSequence text,int length){if(c==null||length!=LENGTH_SHORT)throw new AssertionError("short toast requires context");Toast toast=new Toast();toast.text=text.toString();return toast;}public void show(){if(denied)throw new IllegalStateException();shown.add(text);}}''',
"android/widget/TextView.java": '''package android.widget;public class TextView{public String text;public void setText(int value){text=Integer.toString(value);}public void setText(CharSequence value){text=value.toString();}}''',
"android/bluetooth/le/ScanFilter.java": '''package android.bluetooth.le;public class ScanFilter {public String address;public static class Builder{private ScanFilter f=new ScanFilter();public Builder setDeviceAddress(String s){f.address=s;return this;}public ScanFilter build(){return f;}}}''',
"android/bluetooth/le/ScanSettings.java": '''package android.bluetooth.le;public class ScanSettings {public static final int SCAN_MODE_LOW_LATENCY=2;public int mode;public static class Builder{private ScanSettings s=new ScanSettings();public Builder setScanMode(int m){s.mode=m;return this;}public ScanSettings build(){return s;}}}''',
"android/bluetooth/le/BluetoothLeScanner.java": '''package android.bluetooth.le;import java.util.*;public class BluetoothLeScanner {public int starts,stops;public boolean denied,stopDenied;public ScanCallback callback;public List<ScanFilter> filters;public void startScan(List<ScanFilter> f,ScanSettings settings,ScanCallback c){starts++;if(denied)throw new SecurityException();filters=f;callback=c;if(settings.mode!=2)throw new AssertionError("expected bounded active scan");}public void stopScan(ScanCallback c){stops++;if(stopDenied)throw new SecurityException();if(callback==c)callback=null;}}''',
"android/util/Log.java": '''package android.util; public class Log { public static String lastWarning=""; public static final java.util.List<String> messages=new java.util.ArrayList<>(); public static int i(String t,String s){messages.add(s);return 0;} public static int d(String t,String s){messages.add(s);return 0;} public static int w(String t,String s){lastWarning=s;messages.add(s);return 0;} public static int e(String t,String s,Throwable x){messages.add(s);return 0;} }''',
"android/view/View.java": '''package android.view; public class View { public static final int VISIBLE=0,GONE=8; public int visibility;public void setVisibility(int value){visibility=value;}public boolean shown=true; public boolean isShown(){return shown;} public int getWindowVisibility(){return 0;} }''',
"android/bluetooth/BluetoothProfile.java": '''package android.bluetooth; public interface BluetoothProfile { int STATE_DISCONNECTED=0, STATE_CONNECTED=2; }''',
"android/bluetooth/BluetoothGattCallback.java": '''package android.bluetooth; public class BluetoothGattCallback { public void onConnectionStateChange(BluetoothGatt g,int s,int n){} public void onServicesDiscovered(BluetoothGatt g,int s){} public void onDescriptorWrite(BluetoothGatt g,BluetoothGattDescriptor d,int s){} public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c){} public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] b){} public void onCharacteristicWrite(BluetoothGatt g,BluetoothGattCharacteristic c,int s){} public void onCharacteristicRead(BluetoothGatt g,BluetoothGattCharacteristic c,int s){}public void onCharacteristicRead(BluetoothGatt g,BluetoothGattCharacteristic c,byte[] b,int s){} }''',
"android/bluetooth/BluetoothGattDescriptor.java": '''package android.bluetooth; import java.util.*; public class BluetoothGattDescriptor { public static final byte[] ENABLE_NOTIFICATION_VALUE={1,0}; public byte[] value; public void setValue(byte[] b){value=b.clone();} public UUID getUuid(){return UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");}public int getPermissions(){return 16;} }''',
"android/bluetooth/BluetoothGattCharacteristic.java": '''package android.bluetooth; import java.util.*;
public class BluetoothGattCharacteristic {
 public static final int PROPERTY_READ=2,PROPERTY_WRITE_NO_RESPONSE=4,PROPERTY_WRITE=8,PROPERTY_NOTIFY=16,WRITE_TYPE_NO_RESPONSE=1,WRITE_TYPE_DEFAULT=2;
 private final UUID id; private final int properties; public int writeType; private byte[] value; public BluetoothGattDescriptor descriptor; BluetoothGattService service;
 public BluetoothGattCharacteristic(UUID u,int p,boolean cccd){id=u;properties=p;descriptor=cccd?new BluetoothGattDescriptor():null;}
 public UUID getUuid(){return id;}public int getProperties(){return properties;}public BluetoothGattDescriptor getDescriptor(UUID u){return descriptor;}public BluetoothGattService getService(){return service;}public int getInstanceId(){return 1;}public int getPermissions(){return 0;}public List<BluetoothGattDescriptor> getDescriptors(){return descriptor==null?Collections.emptyList():Arrays.asList(descriptor);}
 public byte[] getValue(){return value;}public boolean setValue(byte[] b){value=b.clone();return true;}public void setWriteType(int t){writeType=t;}
}''',
"android/bluetooth/BluetoothGattService.java": '''package android.bluetooth;import java.util.*;public class BluetoothGattService { private UUID id; private List<BluetoothGattCharacteristic> cs=new ArrayList<>();public BluetoothGattService(UUID id){this.id=id;}public UUID getUuid(){return id;}public int getInstanceId(){return 1;}public int getType(){return 0;}public List<BluetoothGattCharacteristic> getCharacteristics(){return cs;}public void add(BluetoothGattCharacteristic c){c.service=this;cs.add(c);} }''',
"android/bluetooth/BluetoothGatt.java": '''package android.bluetooth;import java.util.*;import android.os.*;public class BluetoothGatt {
 public static final int GATT_SUCCESS=0,CONNECTION_PRIORITY_HIGH=1; public BluetoothGattCallback callback;public List<BluetoothGattService> services=new ArrayList<>();public List<String> writes=new ArrayList<>();public List<Long> writeTimes=new ArrayList<>();public List<Integer> types=new ArrayList<>(),priorityRequests=new ArrayList<>();public List<String> reads=new ArrayList<>();public BluetoothGattDescriptor pendingDescriptor;public BluetoothGattCharacteristic lastWrite,lastRead;public boolean closed,autoWrite=true,rejectWrite,denyWrite,autoRead=true,autoNotify,notifyFirst=true,vendorLengthBug,priorityAccepted=true;public int writeStatus,readStatus,disconnectCalls,closeCalls;public boolean disconnectDenied,closeDenied;public long writeDelayMs,notifyDelayMs,readDelayMs;public byte[] voltage="CMD|7|12000|$".getBytes(java.nio.charset.StandardCharsets.US_ASCII);
 public List<BluetoothGattService> getServices(){return services;}public boolean discoverServices(){return true;}public boolean setCharacteristicNotification(BluetoothGattCharacteristic c,boolean b){return true;}public boolean writeDescriptor(BluetoothGattDescriptor d){pendingDescriptor=d;return true;}
 public boolean writeCharacteristic(BluetoothGattCharacteristic c){if(denyWrite)throw new SecurityException();if(rejectWrite)return false;lastWrite=c;String data=new String(c.getValue(),java.nio.charset.StandardCharsets.US_ASCII);writes.add(data);writeTimes.add(Handler.now);types.add(c.writeType);int result=vendorLengthBug&&c.getValue().length>1?13:writeStatus;Handler h=new Handler(Looper.getMainLooper());boolean feedback=autoNotify&&data.equals("CMD|7|$");if(feedback&&notifyFirst)h.postDelayed(()->callback.onCharacteristicChanged(this,c,voltage),notifyDelayMs);if(autoWrite)h.postDelayed(()->callback.onCharacteristicWrite(this,c,result),writeDelayMs);if(feedback&&!notifyFirst)h.postDelayed(()->callback.onCharacteristicChanged(this,c,voltage),notifyDelayMs);return true;}
 public boolean readCharacteristic(BluetoothGattCharacteristic c){lastRead=c;reads.add(c.getUuid().toString());if(autoRead)new Handler(Looper.getMainLooper()).postDelayed(()->callback.onCharacteristicRead(this,c,readStatus),readDelayMs);return true;}
 public boolean requestConnectionPriority(int priority){priorityRequests.add(priority);return priorityAccepted;}
 public void disconnect(){disconnectCalls++;if(disconnectDenied)throw new SecurityException();}public void close(){closeCalls++;closed=true;if(closeDenied)throw new SecurityException();}public void completeDescriptor(int status){callback.onDescriptorWrite(this,pendingDescriptor,status);}public void discover(){callback.onConnectionStateChange(this,0,2);Handler.advance(0);callback.onServicesDiscovered(this,0);Handler.advance(0);}
}''',
"android/bluetooth/BluetoothDevice.java": '''package android.bluetooth;import android.content.*;public class BluetoothDevice { public static final int TRANSPORT_LE=2;public BluetoothGatt fake;public String address="12:34:56:78:9A:BC";public int connects;private String name;public BluetoothDevice(String n,BluetoothGatt g){name=n;fake=g;}public String getName(){return name;}public String getAddress(){return address;}public BluetoothGatt connectGatt(Context c,boolean a,BluetoothGattCallback cb,int transport){if(a||transport!=TRANSPORT_LE)throw new AssertionError("not explicit BLE connection");connects++;fake.callback=cb;return fake;} }''',
}

TEST = r'''package com.mvtbot.link;
import android.bluetooth.*;import android.os.*;import android.content.*;import android.view.*;import java.util.*;import java.nio.charset.StandardCharsets;
public final class BleSessionTest {
 static int checks;static List<String> frames=new ArrayList<>();static List<Integer> events=new ArrayList<>();static Context ctx=new Context();static View view=new View();static int resets;
 static MiniBalanLink.ControlReset owner=()->resets++;static Message lastTrusted;static boolean simulatePidEcho,echoHandled;
 static Handler ui=new Handler(m->{if(MiniBalanLink.acceptUiEvent(m)){lastTrusted=m;events.add(m.what);if(m.what==103){frames.add((String)m.obj);if(simulatePidEcho&&((String)m.obj).startsWith("CMD|8|"))echoHandled=MiniBalanLink.send("CMD|1|-2.0|$")&&MiniBalanLink.send("CMD|2|1|140|30|$");}}return true;});
 static UUID u(String s){return UUID.fromString("0000"+s+"-0000-1000-8000-00805f9b34fb");}
 static void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}
 static BluetoothGattCharacteristic characteristic(int p,boolean desc){return new BluetoothGattCharacteristic(u("ffe1"),p,desc);}
 static BluetoothGatt make(String service,int props){BluetoothGatt g=new BluetoothGatt();BluetoothGattService s=new BluetoothGattService(u(service));s.add(characteristic(props,true));g.services.add(s);return g;}
 static void profile(BluetoothGatt g,String maker,String model,String fw){BluetoothGattService s=new BluetoothGattService(u("180a"));String[] ids={"2a29","2a24","2a26"},values={maker,model,fw};for(int i=0;i<ids.length;i++){BluetoothGattCharacteristic c=new BluetoothGattCharacteristic(u(ids[i]),2,false);c.setValue(values[i].getBytes(StandardCharsets.US_ASCII));s.add(c);}g.services.add(s);}
 static BluetoothGatt vendor(){BluetoothGatt g=make("ffe0",24);profile(g,"QUALCOMM","HC-05D","1.1.4");g.vendorLengthBug=true;g.autoNotify=true;return g;}
 static void probePending(BluetoothGatt g){g.autoWrite=false;g.autoNotify=false;open(g);g.completeDescriptor(0);Handler.advance(0);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(40);check(g.writes.equals(Arrays.asList("CMD|3|0|0|$","CMD|7|$")),"profile probe sends zero once then original voltage query");check(!MiniBalanLink.isReady(),"profile and query submission alone are not operational");}
 static void open(BluetoothGatt g){MiniBalanLink.destroy();MiniBalanLink.bind(ctx,ui);view.shown=true;MiniBalanLink.bindControl(owner,view);MiniBalanLink.foreground(true);check(MiniBalanLink.connect(new BluetoothDevice("HC-05D",g)),"connect accepted");Handler.advance(0);g.discover();}
 static void ready(BluetoothGatt g){open(g);check(!MiniBalanLink.isReady(),"not ready before CCCD");g.completeDescriptor(0);Handler.advance(60);if(!g.autoWrite){check(!MiniBalanLink.isReady(),"CCCD alone cannot enable controls");g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(40);}if(g.vendorLengthBug)Handler.advance(250);check(MiniBalanLink.isReady(),"ready only after initial write completion and applicable neutral refresh");}
 static void startupRefresh(BluetoothGatt g){Handler.advance(40);check(!MiniBalanLink.isReady(),"profile proof still waits for startup zero1");g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(140);check(!MiniBalanLink.isReady(),"profile startup waits for zero2 completion");g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(40);check(MiniBalanLink.isReady(),"startup dual-zero refresh completes before operational");}
 static long bootSlow(BluetoothGatt g){open(g);g.completeDescriptor(0);for(int i=0;i<10000&&!MiniBalanLink.isReady()&&!g.closed;i++)Handler.advance(1);check(MiniBalanLink.isReady(),"slow startup operational");check(g.writes.subList(0,4).equals(Arrays.asList("CMD|3|0|0|$","CMD|7|$","CMD|3|0|0|$","CMD|3|0|0|$")),"slow startup zero/query/refresh order");check(g.writeTimes.get(3)-g.writeTimes.get(2)>=100+g.writeDelayMs,"startup zero2 waits for zero1 completion and gap");check(Handler.now-g.writeTimes.get(3)>=g.writeDelayMs,"operational waits for startup zero2 completion");return Handler.now;}
 static int connectedEvents(){return Collections.frequency(events,3);}
 static void receive(BluetoothGatt g,String text){BluetoothGattCharacteristic c=g.services.get(0).getCharacteristics().get(0);g.callback.onCharacteristicChanged(g,c,text.getBytes(StandardCharsets.US_ASCII));Handler.advance(0);}
 public static void main(String[] args) throws Exception {
  BluetoothGatt g=make("e0ff",20);ready(g);check(g.types.get(0)==1,"WWR preferred");check(g.writes.get(0).equals("CMD|3|0|0|$"),"first zero");
  receive(g,"CMD|4|1|");check(frames.isEmpty(),"partial withheld");receive(g,"2|$CMD|5|23|$");check(frames.size()==2,"fragmented and glued frames decoded");receive(g,"CMD|4|-1\u0000|3|$");check(frames.size()==2,"NUL rejected");check(android.util.Log.lastWarning.contains("raw=")&&android.util.Log.lastWarning.contains("00")&&android.util.Log.lastWarning.contains("count="),"raw NUL diagnostics available");receive(g,"CMD|4|1|2$");check(frames.get(frames.size()-1).equals("CMD|4|1|2|$"),"canonical legacy presentation separator");
  check(!MiniBalanLink.send("CMD|3|1|0|$"),"generic path cannot arm motion");
  int before=g.writes.size();MiniBalanLink.motion(owner,1,0);Handler.advance(90);check(g.writes.get(before).equals("CMD|3|0|0|$"),"first arm zero barrier");check(!g.writes.contains("CMD|3|1|0|$"),"motion withheld between arm zeros");Handler.advance(100);check(g.writes.get(before+1).equals("CMD|3|0|0|$"),"second independent arm zero");check(g.writeTimes.get(before+1)-g.writeTimes.get(before)>=100,"arm zeros separated by at least 100ms");check(g.writes.contains("CMD|3|1|0|$"),"fresh motion after both zeros");
  MiniBalanLink.release();Handler.advance(100);check(g.writes.get(g.writes.size()-1).equals("CMD|3|0|0|$"),"release zero");int stopped=g.writes.size();Handler.advance(600);check(g.writes.size()==stopped,"release stops heartbeat");
  MiniBalanLink.motion(owner,-1,0);Handler.advance(200);view.shown=false;Handler.advance(150);check(g.writes.get(g.writes.size()-1).equals("CMD|3|0|0|$"),"hidden view zero");stopped=g.writes.size();Handler.advance(300);check(g.writes.size()==stopped,"hidden heartbeat stopped");
  BluetoothGatt old=g;g=make("ffe0",28);ready(g);check(g.types.get(0)==1,"original FFE0 supports WWR");int count=frames.size();receive(old,"CMD|5|99|$");check(frames.size()==count,"stale GATT notification ignored");Handler.advance(200);check(g.writes.size()==1,"reconnect does not replay motion");
  MiniBalanLink.foreground(false);MiniBalanLink.motion(owner,1,0);Handler.advance(200);check(g.writes.size()==1,"background cannot arm");MiniBalanLink.foreground(true);
  // Consecutive neutral samples cannot toggle the re-arm gate back on.
  MiniBalanLink.controlMode(owner,1);check(MiniBalanLink.gravity(owner,0,0)==-2,"initial gravity neutral");check(MiniBalanLink.gravity(owner,0,0)==-2,"second gravity neutral");MiniBalanLink.motion(owner,0,0);check(MiniBalanLink.gravity(owner,4,0)==2,"fresh tilt after consecutive neutral samples");Handler.advance(200);
  check(MiniBalanLink.gravity(owner,3.2f,0)==-2,"rounding-gap sample explicitly zero");Handler.advance(100);check(g.writes.get(g.writes.size()-1).equals("CMD|3|0|0|$"),"4 to 3.2 transition stops old vector");
  for(int i=0;i<5;i++)MiniBalanLink.gravity(owner,0,0);check(MiniBalanLink.gravity(owner,4,0)==2,"odd neutral count does not block tilt");Handler.advance(100);MiniBalanLink.gravity(owner,0,0);Handler.advance(100);
  MiniBalanLink.ControlReset oldOwner=owner;owner=()->resets++;MiniBalanLink.bindControl(owner,view);int boundCount=g.writes.size();MiniBalanLink.controlMode(owner,1);MiniBalanLink.gravity(oldOwner,0,0);MiniBalanLink.gravity(oldOwner,4,0);MiniBalanLink.motion(oldOwner,1,0);Handler.advance(200);check(g.writes.size()==boundCount,"old sensor/joystick owner cannot move new view");
  MiniBalanLink.controlMode(owner,2);MiniBalanLink.gravity(owner,0,0);MiniBalanLink.gravity(owner,4,0);Handler.advance(200);check(g.writes.size()==boundCount,"queued gravity event ignored in joystick mode");
  for(int code:new int[]{3,4,5,6,11,13,15,16,21,78,86,87,92,101,103,104}){Message m=ui.obtainMessage(code,"CMD|7|bad|$");check(!MiniBalanLink.acceptUiEvent(m),"queued legacy BLE event rejected "+code);}check(MiniBalanLink.acceptUiEvent(ui.obtainMessage(20,null)),"UI ticker 20 preserved");check(!MiniBalanLink.acceptUiEvent(lastTrusted),"trusted event cannot be replayed outside guarded dispatch");
  g=make("e0ff",24);g.autoWrite=false;ready(g);check(g.types.get(0)==2,"response fallback");int serialBase=g.writes.size();MiniBalanLink.send("CMD|7|$");MiniBalanLink.send("CMD|8|1|$");Handler.advance(100);check(g.writes.size()==serialBase+1,"response serial queue");g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(40);check(g.writes.size()==serialBase+2,"response callback advances queue");Handler.advance(800);check(!MiniBalanLink.isReady()&&g.closed,"write timeout disconnects");
  g=make("e0ff",20);open(g);g.completeDescriptor(5);Handler.advance(0);check(!MiniBalanLink.isReady()&&g.closed,"failed CCCD rejected");
  g=make("e0ff",20);open(g);Handler.advance(10001);check(!MiniBalanLink.isReady()&&g.closed,"total connect timeout");
  g=make("e0ff",20);g.services.get(0).add(characteristic(4,false));open(g);check(g.closed,"ambiguous write handles rejected");
  g=make("e0ff",4);g.services.get(0).add(characteristic(16,true));ready(g);check(g.types.get(0)==1,"separate same-UUID write and notify handles accepted");
  g=make("ffe0",20);BluetoothGattService preferred=new BluetoothGattService(u("e0ff"));preferred.add(characteristic(20,true));g.services.add(preferred);ready(g);check(g.lastWrite.getService()==preferred,"E0FF preference");
  g=make("e0ff",24);g.autoWrite=false;ready(g);for(int i=0;i<26;i++)MiniBalanLink.send("CMD|7|$");check(!MiniBalanLink.isReady()&&g.closed,"bounded queue fails closed");
  g=make("e0ff",20);ready(g);g.rejectWrite=true;MiniBalanLink.send("CMD|7|$");Handler.advance(100);check(!MiniBalanLink.isReady(),"GATT enqueue rejection handled");
  g=make("e0ff",20);g.rejectWrite=true;open(g);g.completeDescriptor(0);Handler.advance(60);check(!MiniBalanLink.isReady()&&g.closed,"first zero enqueue failure cannot crash readiness callback");
  g=make("e0ff",20);g.denyWrite=true;open(g);g.completeDescriptor(0);Handler.advance(60);check(!MiniBalanLink.isReady()&&g.closed,"first zero permission failure cannot crash readiness callback");
  for(int status:new int[]{3,5,15,133}){g=make("ffe0",24);g.writeStatus=status;int connectedBefore=connectedEvents();open(g);g.completeDescriptor(0);Handler.advance(100);String diagnostic=android.util.Log.lastWarning;check(!MiniBalanLink.isReady()&&g.closed,"write callback failure still closes for status "+status);check(diagnostic.contains("status="+status+"(0x"+Integer.toHexString(status)+")")&&diagnostic.contains("writeType=2")&&diagnostic.contains("props=0x18"),"write failure numeric code/mode/properties logged");check(diagnostic.contains("offset=0")&&diagnostic.contains("len=11")&&diagnostic.contains("frameLen=11")&&diagnostic.contains("waitingResponse=true")&&diagnostic.contains("latestSubmission=1"),"failed first zero queue/chunk context logged");check(g.writes.size()==1&&g.types.get(0)==2,"non-13 diagnostic does not retry or invent unsupported WWR mode");check(connectedEvents()==connectedBefore&&events.get(events.size()-1)==4,"failed setup never emits connected and reports failure4");}
  check(android.util.Log.messages.stream().anyMatch(s->s.contains("GATT service: uuid=0000ffe0")&&s.contains("type=0")),"service metadata logged");check(android.util.Log.messages.stream().anyMatch(s->s.contains("GATT characteristic:")&&s.contains("props=0x18")&&s.contains("descriptors=1")),"characteristic metadata logged");check(android.util.Log.messages.stream().anyMatch(s->s.contains("GATT descriptor:")&&s.contains("uuid=00002902")&&s.contains("permissions=0x10")),"descriptor metadata logged");
  check(!MiniBalanLink.connect(null,ui,new BluetoothDevice("PRIVATE-NAME-AA:BB:CC:DD:EE:FF",make("ffe0",24))),"missing context remains rejected");check(android.util.Log.lastWarning.contains("contextPresent=false")&&android.util.Log.lastWarning.contains("handlerPresent=true")&&android.util.Log.lastWarning.contains("devicePresent=true"),"early rejection identifies missing binding without identity");check(!MiniBalanLink.connect(ctx,null,new BluetoothDevice("PRIVATE-NAME-AA:BB:CC:DD:EE:FF",make("ffe0",24))),"missing handler remains rejected");check(android.util.Log.lastWarning.contains("handlerPresent=false"),"missing handler logged");check(!MiniBalanLink.connect(ctx,ui,null),"missing device remains rejected");check(android.util.Log.lastWarning.contains("devicePresent=false"),"missing device logged");check(android.util.Log.messages.stream().noneMatch(s->s.contains("PRIVATE-NAME")||s.contains("AA:BB:CC:DD:EE:FF")),"diagnostics do not log device name or address");
  // HC-05D firmware compatibility: exact DIS plus an actual voltage round trip.
  int compatEvents=connectedEvents();g=vendor();ready(g);check(g.reads.equals(Arrays.asList(u("2a29").toString(),u("2a24").toString(),u("2a26").toString())),"three non-identity DIS fields read serially");check(g.writes.equals(Arrays.asList("CMD|3|0|0|$","CMD|7|$","CMD|3|0|0|$","CMD|3|0|0|$")),"profile proof followed by independent startup double zero without padding");check(g.types.equals(Arrays.asList(2,2,2,2))&&connectedEvents()==compatEvents+1,"response mode and closed-loop operational gate");check(android.util.Log.messages.stream().anyMatch(x->x.contains("not security authentication")),"DIS allowlist is not called authentication");
  g=vendor();g.notifyFirst=false;ready(g);check(MiniBalanLink.isReady(),"write completion before notification also validates");
  g=vendor();probePending(g);receive(g,"CMD|7|12020|$");check(!MiniBalanLink.isReady(),"notification alone never opens controls");int pendingCount=g.writes.size();check(!MiniBalanLink.send("CMD|7|$"),"public queries blocked before operational");g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);startupRefresh(g);check(MiniBalanLink.isReady()&&Collections.frequency(g.writes,"CMD|7|$")==1,"proof and startup refresh open once without duplicate query");
  g=vendor();probePending(g);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);check(!MiniBalanLink.isReady(),"vendor completion alone does not open controls");receive(g,"CMD|7|12140|$");startupRefresh(g);check(MiniBalanLink.isReady(),"completion then voltage opens controls");
  g=vendor();probePending(g);g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(0);check(!MiniBalanLink.isReady(),"normal callback still needs voltage");receive(g,"CMD|7|12001$");startupRefresh(g);check(MiniBalanLink.isReady(),"optional separator and one-mV precision supported");
  for(String[] wrong:new String[][]{{"OTHER","HC-05D","1.1.4"},{"QUALCOMM","OTHER","1.1.4"},{"QUALCOMM","HC-05D","1.1.5"}}){g=make("ffe0",24);profile(g,wrong[0],wrong[1],wrong[2]);g.vendorLengthBug=true;compatEvents=connectedEvents();open(g);g.completeDescriptor(0);Handler.advance(100);check(g.closed&&g.writes.size()==1&&connectedEvents()==compatEvents,"mismatching DIS never permits vendor completion");}
  g=make("ffe0",24);g.vendorLengthBug=true;open(g);g.completeDescriptor(0);Handler.advance(100);check(g.closed&&g.writes.size()==1,"missing DIS rejects compatibility");
  g=vendor();g.readStatus=5;open(g);g.completeDescriptor(0);Handler.advance(100);check(g.closed&&g.writes.size()==1,"DIS authentication failure is never adapted");
  for(int props:new int[]{20,26}){g=make("ffe0",props);profile(g,"QUALCOMM","HC-05D","1.1.4");g.writeStatus=13;open(g);g.completeDescriptor(0);Handler.advance(100);check(g.closed&&g.writes.size()==1&&g.reads.isEmpty(),"WWR or nonexact properties cannot enter compatibility");}
  g=make("e0ff",24);profile(g,"QUALCOMM","HC-05D","1.1.4");g.writeStatus=13;open(g);g.completeDescriptor(0);Handler.advance(100);check(g.closed&&g.reads.isEmpty(),"unverified E0FF anomaly never inherits FFE0 quirk");
  g=make("ffe0",8);g.services.get(0).add(characteristic(16,true));profile(g,"QUALCOMM","HC-05D","1.1.4");g.writeStatus=13;open(g);g.completeDescriptor(0);Handler.advance(100);check(g.closed&&g.reads.isEmpty(),"split write/notify characteristic cannot qualify");
  for(String invalid:new String[]{"CMD|7|-1|$","CMD|7|40001|$","CMD|7|2147483647|$","CMD|7|12\u0000|$","CMD|4|1|2|$"}){g=vendor();probePending(g);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);receive(g,invalid);check(!MiniBalanLink.isReady(),"invalid/non-voltage notification cannot establish health");Handler.advance(1501);check(g.closed,"missing valid voltage times out");}
  // A frame captured before actual query submission must not pass a later queue window.
  g=vendor();g.autoRead=false;g.autoWrite=false;g.autoNotify=false;open(g);g.completeDescriptor(0);Handler.advance(40);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);g.callback.onCharacteristicRead(g,g.lastRead,0);Handler.advance(0);g.callback.onCharacteristicRead(g,g.lastRead,0);Handler.advance(0);g.callback.onCharacteristicRead(g,g.lastRead,0);BluetoothGattCharacteristic tx=g.services.get(0).getCharacteristics().get(0);g.callback.onCharacteristicChanged(g,tx,"CMD|7|11999|$".getBytes(StandardCharsets.US_ASCII));Handler.advance(0);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);check(!MiniBalanLink.isReady(),"pre-submission queued notification cannot validate profile");receive(g,"CMD|7|12020|$");startupRefresh(g);check(MiniBalanLink.isReady(),"fresh post-submission notification validates profile");
  g=vendor();g.autoRead=false;g.autoWrite=false;g.autoNotify=false;open(g);g.completeDescriptor(0);Handler.advance(40);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);receive(g,"CMD|7|12");for(int i=0;i<3;i++){g.callback.onCharacteristicRead(g,g.lastRead,0);Handler.advance(0);}g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);receive(g,"020|$");check(!MiniBalanLink.isReady(),"half frame from before query cannot finish handshake");receive(g,"CMD|7|12020|$");startupRefresh(g);check(MiniBalanLink.isReady(),"new complete frame after rejected half frame accepted");
  g=vendor();probePending(g);receive(g,"CMD|7|12000|$");Handler.advance(751);check(g.closed&&!MiniBalanLink.isReady(),"notification without write completion still fails");
  for(int error:new int[]{3,5,15,133}){g=vendor();probePending(g);receive(g,"CMD|7|12000|$");g.callback.onCharacteristicWrite(g,g.lastWrite,error);Handler.advance(0);check(g.closed&&!MiniBalanLink.isReady(),"probe non13 error always fails despite telemetry");}
  for(int field=0;field<3;field++){g=vendor();g.autoRead=false;open(g);g.completeDescriptor(0);Handler.advance(40);for(int i=0;i<field;i++){g.callback.onCharacteristicRead(g,g.lastRead,0);Handler.advance(0);}int sent=g.writes.size();BluetoothGattCharacteristic pendingRead=g.lastRead;MiniBalanLink.stop();g.callback.onCharacteristicRead(g,pendingRead,0);Handler.advance(100);check(g.closed&&g.writes.size()==sent&&!MiniBalanLink.isReady(),"cancel each DIS stage without further writes");}
  BluetoothGatt oldProfile=vendor();oldProfile.autoRead=false;open(oldProfile);oldProfile.completeDescriptor(0);Handler.advance(40);BluetoothGatt newStandard=make("ffe0",24);ready(newStandard);oldProfile.callback.onCharacteristicRead(oldProfile,oldProfile.lastRead,0);Handler.advance(0);check(MiniBalanLink.isReady()&&newStandard.writes.size()==1,"old profile callback cannot affect replacement session");
  // Runtime: one query at a time, duplicates coalesced, receive time is the clock origin.
  g=vendor();ready(g);g.autoNotify=false;Handler.advance(1000);int queryWrites=g.writes.size();for(int i=0;i<10;i++)MiniBalanLink.send("CMD|7|$");Handler.advance(0);check(g.writes.size()==queryWrites,"legacy ticker and health scheduler share one query");receive(g,"CMD|7|12020|$");Handler.advance(500);receive(g,"CMD|7|12020|$");Handler.advance(1999);check(MiniBalanLink.isReady(),"before 2500ms since valid query notification remains online");Handler.advance(1);check(MiniBalanLink.isReady()&&!g.closed,"2500ms stale proof permits one bounded query retry");Handler.advance(1600);check(g.closed&&!MiniBalanLink.isReady(),"unsolicited duplicate cannot rescue retry without new voltage proof");
  g=vendor();ready(g);g.autoNotify=false;g.autoWrite=false;Handler.advance(1000);receive(g,"CMD|7|12020|$");int held=g.writes.size();MiniBalanLink.send("CMD|7|$");Handler.advance(200);check(g.writes.size()==held,"notification before callback does not permit a second query");g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(0);g.autoWrite=true;Handler.advance(2299);check(MiniBalanLink.isReady(),"delayed callback cannot shift receive freshness deadline");Handler.advance(1);check(!g.closed,"2500ms starts recovery instead of truncating current query");Handler.advance(1600);check(g.closed,"missing voltage after one retry still closes");
  g=vendor();ready(g);String longCommand="CMD|1|1.234567890123456789|$";int splitStart=g.writes.size();MiniBalanLink.send(longCommand);Handler.advance(100);check(g.writes.get(splitStart).equals(longCommand.substring(0,20))&&g.writes.get(splitStart+1).equals(longCommand.substring(20)),"compatibility preserves real final fragment length without padding");check(MiniBalanLink.isReady(),"valid multibyte 13 completion is profile-scoped");
  String pid="CMD|8|-2|140|30|5|450|80|500|$";check(ProtocolValidation.validTelemetry(pid),"PID response fixture valid");g.autoNotify=false;receive(g,pid.substring(0,19));Handler.advance(1000);receive(g,pid.substring(19));check(frames.get(frames.size()-1).equals(pid),"health submission does not erase fragmented PID telemetry");receive(g,"CMD|7|12020|$");check(MiniBalanLink.isReady(),"PID fragments cannot replace voltage proof");
  g=vendor();ready(g);MiniBalanLink.motion(owner,1,0);Handler.advance(2200);check(MiniBalanLink.isReady()&&Collections.frequency(g.writes,"CMD|7|$")>=3,"continuous movement does not starve health queries");g.autoNotify=false;Handler.advance(4500);check(!MiniBalanLink.isReady()&&g.closed,"health loss closes after bounded read-only recovery during movement");int afterHealthFailure=g.writes.size();Handler.advance(500);check(g.writes.size()==afterHealthFailure,"health failure clears all movement and retry tasks");
  g=vendor();ready(g);g.vendorLengthBug=false;g.writeStatus=13;MiniBalanLink.send("CMD|2|1|000000|0000|$");Handler.advance(100);check(g.closed&&g.writes.get(g.writes.size()-1).length()==1,"unexpected status13 for one-byte tail still fails");
  for(int error:new int[]{3,5,15,133}){g=vendor();ready(g);g.vendorLengthBug=false;g.writeStatus=error;int calls=g.writes.size();MiniBalanLink.send("CMD|2|1|1|1|$");Handler.advance(100);check(g.closed&&g.writes.size()==calls+1,"runtime non13 error fails without retrying PID");}
  g=make("ffe0",24);profile(g,"QUALCOMM","HC-05D","1.1.4");ready(g);g.writeStatus=13;MiniBalanLink.send("CMD|2|1|1|1|$");Handler.advance(100);check(g.closed&&g.reads.isEmpty(),"only the first zero13 may begin compatibility detection");
  g=vendor();ready(g);BluetoothGatt fresh=make("ffe0",24);fresh.writeStatus=13;open(fresh);fresh.completeDescriptor(0);Handler.advance(100);check(fresh.closed,"reconnect cannot reuse previously verified DIS profile");
  g=vendor();g.autoRead=false;open(g);g.completeDescriptor(0);Handler.advance(800);check(g.closed,"missing DIS read callback times out");
  g=vendor();g.autoWrite=false;g.autoNotify=false;open(g);Handler.advance(9300);g.completeDescriptor(0);Handler.advance(600);g.callback.onCharacteristicWrite(g,g.lastWrite,13);Handler.advance(200);check(g.closed&&!MiniBalanLink.isReady(),"total 10s setup deadline covers DIS and voltage proof");
  // Slow negotiated links: bounded requests, fair query scheduling and measured lease limits.
  for(long delay:new long[]{90,180,270,360,450}){g=vendor();g.writeDelayMs=delay;g.readDelayMs=90;g.notifyDelayMs=90;bootSlow(g);check(g.priorityRequests.size()==1,"only first HIGH request at startup");MiniBalanLink.motion(owner,1,0);Handler.advance(5000);check(MiniBalanLink.isReady()&&Collections.frequency(g.writes,"CMD|7|$")>=3,"slow callbacks do not starve voltage health");check(g.priorityRequests.equals(Arrays.asList(1,1)),"HIGH bounded to connect and operational+1s");long previous=-1,maxGap=0;for(int i=0;i<g.writes.size();i++)if(g.writes.get(i).equals("CMD|3|1|0|$")){if(previous>=0)maxGap=Math.max(maxGap,g.writeTimes.get(i)-previous);previous=g.writeTimes.get(i);}check(previous>=0,"motion queue makes progress on slow link");if(delay<=180)check(maxGap<500,"responsive slow link stays inside MCU500 lease");else check(maxGap>=500,"very slow response link explicitly exceeds fixed MCU lease");System.out.println("SLOW callbackMs="+delay+" maximumMotionGapMs="+maxGap+" MCU500LeaseGuaranteed="+(maxGap<500));int stoppedAt=g.writes.size();MiniBalanLink.release();Handler.advance(delay+1);check(g.writes.size()>stoppedAt&&g.writes.get(stoppedAt).equals("CMD|3|0|0|$"),"stop remains next operation despite health arbitration");}
  g=vendor();g.priorityAccepted=false;bootSlow(g);Handler.advance(3500);check(g.priorityRequests.size()==2&&MiniBalanLink.isReady(),"HIGH API denial is not assumed successful or retried forever");
  BluetoothGatt oldPriority=vendor();bootSlow(oldPriority);g=vendor();bootSlow(g);Handler.advance(2000);check(oldPriority.priorityRequests.size()==1&&g.priorityRequests.size()==2,"old-session HIGH retry cannot apply to replacement");
  for(int phase:new int[]{2,3}){g=vendor();g.writeDelayMs=450;g.notifyDelayMs=90;g.readDelayMs=90;open(g);g.completeDescriptor(0);while(g.writes.size()<=phase&&!g.closed)Handler.advance(1);check(!MiniBalanLink.isReady(),"not operational during startup refresh phase");int beforeStop=g.writes.size();MiniBalanLink.stop();Handler.advance(1800);check(g.closed&&!MiniBalanLink.isReady()&&g.writes.size()==beforeStop,"startup cancel prevents late operational");}
  g=vendor();g.writeDelayMs=180;g.notifyDelayMs=450;g.readDelayMs=90;bootSlow(g);Handler.advance(4000);check(MiniBalanLink.isReady(),"late notifications and slow responses remain within query budget");
  g=make("ffe0",24);g.autoWrite=false;ready(g);MiniBalanLink.send("CMD|7|$");MiniBalanLink.send("CMD|8|1|$");Handler.advance(180);long returnedAt=Handler.now;g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(0);check(g.writeTimes.get(g.writeTimes.size()-1)==returnedAt,"completed slow write pumps immediately without redundant30ms");
  g=vendor();ready(g);simulatePidEcho=true;echoHandled=false;int beforeEcho=g.writes.size();receive(g,"CMD|8|-2.0|140|30|5|450|80|500|$");Handler.advance(100);check(echoHandled&&g.writes.size()==beforeEcho,"PID presentation handles but does not transmit CMD1/CMD2 echoes");simulatePidEcho=false;check(MiniBalanLink.send("CMD|1|-2.0|$")&&MiniBalanLink.send("CMD|2|1|140|30|$"),"real user parameter changes still accepted");Handler.advance(100);check(g.writes.contains("CMD|1|-2.0|$")&&g.writes.contains("CMD|2|1|140|30|$"),"real user or arrow writes reach original send path");
  // Quiet DMA epoch: first zero may be discarded; only the second dispatch arms MCU.
  g=make("e0ff",20);ready(g);Handler.advance(600);before=g.writes.size();MiniBalanLink.motion(owner,1,0);Handler.advance(50);MiniBalanLink.motion(owner,-1,0);Handler.advance(160);check(g.writes.get(before).equals("CMD|3|0|0|$")&&g.writes.get(before+1).equals("CMD|3|0|0|$"),"idle rearm sends two distinct zeros");check(g.writes.get(before+2).equals("CMD|3|-1|0|$"),"rearm uses latest gesture vector");
  g=make("e0ff",20);ready(g);before=g.writes.size();MiniBalanLink.motion(owner,1,0);Handler.advance(50);MiniBalanLink.release();Handler.advance(400);check(!g.writes.contains("CMD|3|1|0|$"),"release cancels delayed second zero completion");
  g=make("e0ff",20);ready(g);MiniBalanLink.motion(owner,1,0);Handler.advance(50);MiniBalanLink.foreground(false);Handler.advance(400);check(!g.writes.contains("CMD|3|1|0|$"),"pause cancels arm timer");
  g=make("e0ff",20);ready(g);MiniBalanLink.motion(owner,1,0);Handler.advance(50);owner=()->resets++;MiniBalanLink.bindControl(owner,view);Handler.advance(400);check(!g.writes.contains("CMD|3|1|0|$"),"owner replacement cancels old arm timer");
  g=make("e0ff",20);ready(g);MiniBalanLink.motion(owner,1,0);Handler.advance(50);BluetoothGatt replacement=make("e0ff",20);ready(replacement);Handler.advance(400);check(replacement.writes.size()==1,"reconnect cancels both old rearm phases");
  // A delayed completion from gesture A must not clear gesture B's arm barrier.
  g=make("e0ff",24);g.autoWrite=false;ready(g);g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(40);MiniBalanLink.motion(owner,1,0);MiniBalanLink.release();MiniBalanLink.motion(owner,-1,0);g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(40);check(!g.writes.contains("CMD|3|-1|0|$"),"old gesture completion cannot unlock new gesture");g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(140);check(!g.writes.contains("CMD|3|-1|0|$"),"new gesture waits for second response completion");g.callback.onCharacteristicWrite(g,g.lastWrite,0);Handler.advance(40);check(g.writes.get(g.writes.size()-1).equals("CMD|3|-1|0|$"),"new gesture moves only after own second zero completion");
  MiniBalanLink.unregister(ctx,new BroadcastReceiver());MiniBalanLink.unregister(ctx,new BroadcastReceiver());check(ctx.unregisters==2,"unregister idempotent");
  MiniBalanLink.leaveForLegacy();check(!MiniBalanLink.isOwned(),"legacy ownership restored");
  MiniBalanLink.selectMini();check(MiniBalanLink.isOwned()&&!MiniBalanLink.isReady(),"MiniBalan selection claims mode without auto-connecting");check(!MiniBalanLink.beginLegacyOperation(),"previous robot cannot provide selected MiniBalan transport");MiniBalanLink.leaveForLegacy();
  check(MiniBalanLink.beginLegacyDispatch(),"legacy sender entered old generation");check(MiniBalanLink.beginLegacyOperation(),"legacy GATT operation before takeover");MiniBalanLink.endLegacyOperation();
  BluetoothGatt next=make("e0ff",20);MiniBalanLink.connect(ctx,ui,new BluetoothDevice("new",next));next.discover();next.completeDescriptor(0);Handler.advance(60);check(MiniBalanLink.isReady(),"new GATT ready while old sender suspended");
  check(!MiniBalanLink.legacyDispatchCurrent(),"sleeping sender generation invalidated");check(!MiniBalanLink.beginLegacyOperation(),"old GATT write/reconnect fenced");check(!MiniBalanLink.allowStop(),"legacy failure cannot call stop");MiniBalanLink.stop();Handler.advance(250);check(MiniBalanLink.isReady(),"legacy failure did not close new session");check(!MiniBalanLink.sendBytes("CMD|7|$".getBytes(StandardCharsets.US_ASCII)),"old sender cannot inject into new queue");
  MiniBalanLink.endLegacyDispatch();MiniBalanLink.leaveForLegacy();check(MiniBalanLink.acceptUiEvent(ui.obtainMessage(3,null)),"other robot connection event preserved");check(!MiniBalanLink.acceptUiEvent(ui.obtainMessage(103,"CMD|7|bad|$")),"unmarked MiniBalan telemetry never enters old parser");
  java.util.concurrent.CountDownLatch entered=new java.util.concurrent.CountDownLatch(1);java.util.concurrent.atomic.AtomicBoolean finished=new java.util.concurrent.atomic.AtomicBoolean();java.util.concurrent.atomic.AtomicReference<Throwable> failure=new java.util.concurrent.atomic.AtomicReference<>();
  Thread legacy=new Thread(()->{try{if(!MiniBalanLink.beginLegacyDispatch()||!MiniBalanLink.beginLegacyOperation())throw new AssertionError("legacy gate acquisition");entered.countDown();Thread.sleep(40);if(MiniBalanLink.isOwned())throw new AssertionError("ownership changed inside old GATT operation");MiniBalanLink.endLegacyOperation();MiniBalanLink.endLegacyDispatch();finished.set(true);}catch(Throwable t){failure.set(t);entered.countDown();}});legacy.start();entered.await();MiniBalanLink.connect(ctx,ui,new BluetoothDevice("gated",make("e0ff",20)));legacy.join();check(failure.get()==null&&finished.get()&&MiniBalanLink.isOwned(),"atomic legacy GATT operation versus ownership takeover");MiniBalanLink.destroy();
  System.out.println("BLE session replay: PASS ("+checks+" assertions)");
 }
}'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--java-home', type=Path, required=True)
    args = parser.parse_args()
    link = Path(__file__).resolve().parents[1]
    suffix = '.exe' if (args.java_home / 'bin/javac.exe').exists() else ''
    with tempfile.TemporaryDirectory(prefix='mvtbot-ble-test-') as temp:
        root = Path(temp)
        files = []
        for name, source in STUBS.items():
            p = root / name
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(source, encoding='utf-8')
            files.append(p)
        test = root / 'com/mvtbot/link/BleSessionTest.java'
        test.parent.mkdir(parents=True, exist_ok=True)
        test.write_text(TEST, encoding='utf-8')
        sources = sorted((link / 'src').rglob('*.java'))
        classes = root / 'classes'
        classes.mkdir()
        subprocess.run([str(args.java_home / ('bin/javac' + suffix)), '-encoding', 'UTF-8', '-d', str(classes), *map(str, files + sources + [test])], check=True)
        subprocess.run([str(args.java_home / ('bin/java' + suffix)), '-cp', str(classes), 'com.mvtbot.link.BleSessionTest'], check=True)


if __name__ == '__main__':
    main()
